site_name: My Docs
plugins:
  - search
extra_javascript:
  - javascripts/extra.js
theme:
  name: material
  language: zh
  font:
    text: Inconsolata
  palette:
    primary: orange
nav:
  - 'Data Structure':
      - 'Array': 'data_structure/array.md'
      - 'Linked List': 'data_structure/linked_list.md'
      - 'Recursive': 'data_structure/recursive.md'
      - 'Sort': 'data_structure/sort.md'
  - 'Collection':
      - 'Hashmap': 'collection/hashmap.md'
      - 'List': 'collection/list.md'
  - 'Concurrency':
      - 'Volatile': 'concurrency/volatile.md'
      - 'Synchronized': 'concurrency/synchronized.md'
  - 'JVM':
      - 'Class Loader': 'jvm/class_loader.md'
      - 'GC': 'jvm/gc.md'
  - 'Design Pattern':
      - 'Singleton': 'design_pattern/singleton.md'
      - 'Factory': 'design_pattern/factory.md'
      - 'Builder': 'design_pattern/builder.md'
      - 'Prototype': 'design_pattern/prototype.md'
      - 'Proxy': 'design_pattern/proxy.md'
      - 'Bridge': 'design_pattern/bridge.md'
      - 'Decorator': 'design_pattern/decorator.md'
      - 'Visitor': 'design_pattern/visitor.md'
  - 'Mysql':
      - 'Transaction': 'mysql/transaction.md'
  - 'Kafka':
      - 'Architecture': 'kafka/architecture.md'
      - 'Semantics': 'kafka/semantics.md'
  - 'Redis':
      - 'Architecture': 'redis/architecture.md'
      - 'Persistence': 'redis/persistence.md'
      - 'Leader Follower': 'redis/leader_follower.md'
      - 'Sentinel': 'redis/sentinel.md'
      - 'Cluster': 'redis/cluster.md'
  - 'System Design':
      - 'Distributed System': 'system_design/distributed_system.md'
      - 'Distributed App Crawler': 'system_design/distributed_app_crawler.md'
  - 'Network':
      - 'Architecture': 'network/architecture.md'
      - 'TCP': 'network/tcp.md'
  - 'MISC':
      - '儒释道': 'misc/儒释道.md'